#
#  Copyright (C) 2022 Odenktools
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  in compliance with the License. You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software distributed under the License
#  is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  or implied. See the License for the specific language governing permissions and limitations under
#  the License.
#
version: '3.6'

services:

  # App PostgreSQL
  pg-tokonya:
    image: tunaiplus/postgres:1.0.0
    container_name: pg-tokonya
    restart: on-failure
    environment:
      POSTGRES_USER: tokonya
      POSTGRES_DB: tokonya
      POSTGRES_PASSWORD: tokonya
    ports:
      - target: 5432
        published: 54301
        protocol: tcp
        mode: host
    volumes:
      - pg-tokonya:/var/lib/postgresql/data
    networks:
      - tokonya-net

  redis-app:
    image: redis:5-alpine
    container_name: redis-app
    volumes:
      - redis-vol:/data
    ports:
      - "6379:6379"
    networks:
      - tokonya-net

  tokonya-app:
    container_name: tokonya-app
    build:
      context: '.'
      args:
        INSTALL_IMAGEMAGICK: 1
        INSTALL_PHPREDIS: 1
    environment:
      - CONTAINER_ROLE=app
    env_file: 
      - .env.docker
    restart: unless-stopped
    ports:
      - "80:80"
      - "9001:9001"
    volumes:
      - .:/var/www/html
      #- ./docker-conf/apache-vhost:/etc/apache2/sites-available
    networks:
      - tokonya-net
    depends_on:
      - pg-tokonya
      - redis-app

volumes:
  pg-tokonya:
    external: true
  redis-vol:
    external: true

networks:
    tokonya-net:
      external: true

#eof